### ISSUE TITLE
How to query consul SRV records

### ISSUE THREAD

**Issue by nbari** [NLnetLabs/ldns#103]
For getting the service records from consul (https://www.consul.io/docs/agent/dns.html#standard-lookup) normally I could do:

    $ dig @10.0.0.2 -p 8600 <service>.service.consul SRV

But I can't find a way to get the records using `drill`

In some cases I get the warning:

    ;; WARNING: The answer packet was truncated; you might want to
    ;; query again with TCP (-t argument), or EDNS0 (-b for buffer size)

but I still can't get the records using option `-t` or -`b` 

Any ideas?

I have been using as an alternative `host`, for example:

    host -t srv consul.service.consul

Trying this in latest stable FreeBSD 12.1, `drill version 1.7.0 (ldns version 1.7.0)`

I am trying querying directly the consul server at port 8600 or an unbound with this configuration:

```
#Allow insecure queries to local resolvers
server:
  do-not-query-localhost: no
  domain-insecure: "consul"

#Add consul as a stub-zone
stub-zone:
  name: "consul"
  stub-addr: 127.0.0.1@8600



```
